# Generated by Django 5.0.3 on 2024-03-12 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrowLivApp', '0003_batch_customuser_batches_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='batches',
        ),
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='GrowLivApp.customuser'),
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
    ]
