# Generated by Django 5.0.3 on 2024-03-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GrowLivApp', '0004_remove_photo_batch_remove_customuser_batches_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
